
theme = "nayfix"

[keys.normal]


#move selection
"A-i" = ["extend_to_line_bounds" , "delete_selection" ,"move_line_up", "paste_before"]
"A-k" = ["extend_to_line_bounds" , "delete_selection" , "paste_after"]


#move word
"C-l" = "move_next_word_start"
"C-j" = "move_prev_word_start"

# mode switch 
"C-x" = "select_mode"
"esc" = "insert_mode"
"A-x" = "command_mode"

# movement keys 
i = "move_visual_line_up"
k = "move_visual_line_down"
j = "move_char_left"
l = "move_char_right"


L = "goto_line_end"
J = "goto_line_start"

#copy , move  and paste
"C-y" = "paste_clipboard_after"
"A-w" = "yank_to_clipboard"
"C-q" = ["yank_to_clipboard" , "delete_selection"]


"C-s" = "search"

"]" = "goto_next_paragraph"
"[" = "goto_prev_paragraph"

[keys.insert]
#move word
"C-l" = "move_char_right"
"C-j" = "move_char_left"
"C-i" = "move_visual_line_up"
"C-k" = "move_visual_line_down"

# mode switch 
"C-x" = "select_mode"
"esc" = "normal_mode"
"A-x" = "command_mode"


"C-y" = "paste_clipboard_before"

                                                      
"A-l" = "goto_line_end"
"A-j" = "goto_line_start"


[keys.select]

# mode switch 
"esc" = "normal_mode"
"C-x" = "normal_mode"
"A-x" = "command_mode"

#move word
"C-l" = "extend_next_word_start"
"C-j" = "extend_prev_word_start"


"A-w" = "yank_to_clipboard"
"C-q" = ["yank_to_clipboard" , "delete_selection"]

L = "goto_line_end"
J = "goto_line_start"

i = "extend_visual_line_up"
k = "extend_visual_line_down"
j = "extend_char_left"
l = "extend_char_right"

[editor.inline-diagnostics]
cursor-line = "warning"
other-lines = "disable"

[editor]
auto-format = false
