
theme = "nayfix"

[keys.normal]


#move selection
"A-k" = ["extend_to_line_bounds" , "delete_selection" ,"move_line_up", "paste_before"]
"A-j" = ["extend_to_line_bounds" , "delete_selection" , "paste_after"]
"A-h" = ["yank_to_clipboard" , "delete_selection" , "move_char_left" , "paste_before"]
"A-l" = ["yank_to_clipboard" , "delete_selection" , "move_char_right" , "paste_after"]


#move word
"C-l" = "move_next_word_start"
"C-h" = "move_prev_word_start"


# mode switch 
"C-x" = ["select_mode"]
"esc" = "insert_mode"
"A-x" = "command_mode"


L = "goto_line_end"
J = "goto_line_start"

#copy , move  and paste
"C-y" = "paste_clipboard_before"
"C-u" = "paste_clipboard_after"

"A-w" = ":clipboard-yank"
"C-w" = ["yank_to_clipboard" , "delete_selection"]

#"tab" = ":fmt"
"ret" = "open_below"
"C-s" = "search"

"C-j" = "goto_next_paragraph"
"C-k" = "goto_prev_paragraph"

[keys.insert]

# mode switch 
"C-x" = "select_mode"
"esc" = "normal_mode"
"A-x" = "command_mode"


"C-y" = "paste_clipboard_before"
"C-u" = "paste_clipboard_after"

                                                      
"A-l" = "goto_line_end"
"A-j" = "goto_line_start"


[keys.select]

# mode switch 
"esc" = "normal_mode"
"C-x" = "normal_mode"
"A-x" = "command_mode"

#move word
"C-l" = "extend_next_word_start"
"C-h" = "extend_prev_word_start"


"A-w" = ":clipboard-yank"
"C-w" = ["yank_to_clipboard" , "delete_selection"]

"C-a" = "select_all"

L = "goto_line_end"
J = "goto_line_start"

k = "extend_visual_line_up"
j = "extend_visual_line_down"
h = "extend_char_left"
l = "extend_char_right"


"C-j" = "goto_next_paragraph"
"C-k" = "goto_prev_paragraph"

#move selection
"A-k" = ["extend_to_line_bounds" , "delete_selection" ,"move_line_up", "paste_before"]
"A-j" = ["extend_to_line_bounds" , "delete_selection" , "paste_after"]
"A-h" = ["yank_to_clipboard" , "delete_selection" , "move_char_left" , "paste_before"]
"A-l" = ["yank_to_clipboard" , "delete_selection" , "move_char_right" , "paste_after"]



[editor.inline-diagnostics]

cursor-line = "warning"
other-lines = "disable"

[editor]

auto-format = false
true-color = true 
line-number = "relative"

[editor.cursor-shape]

normal = "block"
insert = "bar"  


