[[language]]
name = "python"
scope = "source.python"
auto-format = false
language-server = { command = "pylsp" }
config = {}
injection-regex = "python"
file-types = ["py"]
shebangs = ["python"]


[[language]]
name = "c"
file-patterns = ["*.c", "*.h"]
language-servers = ["clangd"]

[language_server.clangd]
command = "clangd"
args = ["--config=clangd.yaml"]
