[[language]]
name = "python"
scope = "source.python"
auto-format = false
diagnostic-severity	= "error"
injection-regex = "python"
file-types = ["py"]
shebangs = ["python"]

[[language]]
name = "c"
file-types = ["*.c", "*.h"]
language-servers = ["clangd"]

[language_server.clangd]
command = "clangd"
args = ["--config=clangd.yaml"]

[language-server.gopls]
command = "gopls"
args = ["serve"]

