
inherits= "naysayer"

"diagnostic" = {fg = "black" , bg = "yellow"}

"diagnostic.hint" = {fg = "black" , bg = "yellow" }

"diagnostic.info" = {fg = "black" , bg = "yellow"}

"diagnostic.warning" = {fg = "black" , bg = "yellow"}
"diagnostic.error" = {fg = "black" , bg = "red"}

"ui.cursor" = {fg = "black" , bg = "#ffa000"}
"ui.cursor.primary" = {fg = "black" , bg = "#ffa000"}
"ui.cursor.match" = {fg = "black" , bg = "green"}
"ui.highlight" = {fg = "black" , bg="red"}
